apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-tutorial-deploy-sc
spec:
  selector:
    matchLabels:
      app: scc-tutorial-sc
  template:
    metadata:
      labels:
        app: scc-tutorial-sc
    spec:
      initContainers:
        - name: init
          image: busybox:1.28
          command: ['sh', '-c', 'if [ ! -d /starlight/data ];then mkdir /starlight/data;fi;if [ ! -d /starlight/runtime ];then mkdir /starlight/runtime;fi;if [ ! -d /starlight/runtime/infiles ];then mkdir /starlight/runtime/infiles;fi;if [ ! -d /starlight/runtime/input ];then mkdir /starlight/runtime/input;fi;if [ ! -d /starlight/data/input ];then mkdir /starlight/data/input;fi;if [ ! -d /starlight/data/output ];then mkdir /starlight/data/output;fi;if [ ! -d /starlight/data/input/processed ];then mkdir /starlight/data/input/processed;fi;if [ ! -d /starlight/runtime/processlist.txt ];then touch /starlight/runtime/processlist.txt;fi']
          volumeMounts:
            - mountPath: /starlight/
              name: ucm-pv-storage
          securityContext:
            runAsUser: 1234
            runAsGroup: 5678
      containers:
        - image: ubi8/ubi-minimal
          name: ubi-minimal
          command:
            ["sh", "-c", 'echo "Hello from user $(id -u)" && sleep infinity']
          securityContext:
            runAsUser: 1234
            runAsGroup: 5678
          volumeMounts:
            - mountPath: /var/opt/app/data
              name: data
      serviceAccountName: default
      securityContext:
        fsGroup: 5555
        supplementalGroups: [5777, 5888]
      volumes:
        - emptyDir: {}
          name: data
        - name: ucm-pv-storage
          persistentVolumeClaim:
            claimName: ucm-pv-claim
