apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlight
  labels:
    app: starlight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starlight
  template:
    metadata:
      labels:
        app: starlight
    spec:
      volumes:
      - name: ucm-pv-storage
        persistentVolumeClaim:
          claimName: ucm-pv-claim
      containers:
      - image: rayc/starlight
        name: starlight
        workingDir: /docker/starlight/STARLIGHTv04
        command: ["./bash_script2.sh"]
        volumeMounts:
        - mountPath: /starlight/
          name: ucm-pv-storage
      - image: rayc/ucm-processor
        name: eventreceiver
        volumeMounts:
        - mountPath: /starlight/
          name: ucm-pv-storage
