apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlight
  labels:
    app: starlight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starlight
  template:
    metadata:
      labels:
        app: starlight
    spec:
      serviceAccountName: starlight-sa
      volumes:
      - name: ucm-pv-storage
        persistentVolumeClaim:
          claimName: ucm-pv-claim
      initContainers:
      - name: init
        image: busybox:1.28
        command: ['sh', '-c', 'if [ ! -d /starlight/data ];then mkdir /starlight/data;fi;if [ ! -d /starlight/runtime ];then mkdir /starlight/runtime;fi;if [ ! -d /starlight/runtime/infiles ];then mkdir /starlight/runtime/infiles;fi;if [ ! -d /starlight/runtime/input ];then mkdir /starlight/runtime/input;fi;if [ ! -d /starlight/data/input ];then mkdir /starlight/data/input;fi;if [ ! -d /starlight/data/output ];then mkdir /starlight/data/output;fi;if [ ! -d /starlight/data/input/processed ];then mkdir /starlight/data/input/processed;fi;if [ ! -d /starlight/runtime/processlist.txt ];then touch /starlight/runtime/processlist.txt;fi']
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /starlight/
          name: ucm-pv-storage
      containers:
      - image: <username>/ucm-processor
        name: starlight
        securityContext:
          privileged: true
        workingDir: /docker/starlight/STARLIGHTv04
        command: ["./bash_script2.sh"]
        volumeMounts:
        - mountPath: /starlight/
          name: ucm-pv-storage
      - image: <username>/ucm-receiver
        name: eventreceiver
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /starlight/
          name: ucm-pv-storage
        env:
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: DATA_FILE_PATH
          value: "/starlight/runtime/input"
        - name: DATA_FILE_FLAG
          value: "/starlight/start_starlight"
        - name: PROCESS_LIST
          value: "/starlight/runtime/processlist.txt" 
      - image: <username>/ucm-watcher
        name: ucm-watcher
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /starlight/
          name: ucm-pv-storage
        env:
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: INPUT_DIR
          value: "/starlight/data/output"
        - name: BATCH_SIZE
          value: "5"
        ports:
        - containerPort: 5672
        
