apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucm-producer-deployment
  labels:
    app: ucm-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucm-producer
  template:
    metadata:
      labels:
        app: ucm-producer
    spec:
      volumes:
      - name: ucm-pv-storage
        persistentVolumeClaim:
          claimName: ucm-pv-claim
      containers:
      - image: valeriiashapoval/ucm
        name: ucm-producer
        env:
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        ports:
        - containerPort: 5672
        volumeMounts:
        - mountPath: /home/starlight/shared_directory/config_files_starlight/
          name: ucm-pv-storage
