name: Pipeline

on: 
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs: 
  build:
    runs-on: ubuntu-latest
    environment: UCM

    strategy:
      matrix:
        image:
          - name: starlight
            tag: latest
            dockerfile: ./processor/starlight/Dockerfile
          - name: receiver
            tag: latest
            dockerfile: ./processor/receiver/Dockerfile
          - name: ucm
            tag: latest
            dockerfile: ./processor/Dockerfile

    env:
      DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with: 
            registry: ${{ env.DOCKER_REGISTRY }}         
            username: ${{ env.DOCKER_USERNAME }}
            password: ${{ env.DOCKER_PASSWORD }}

        - name: Build the Docker image
          uses: docker/build-push-action@v4
          with:
            file: ${{ matrix.image.dockerfile }}
            push: true
            tags: ${{ vars.DOCKER_REPO }}/${{ matrix.image.name }}:${{ matrix.image.tag }}
